Rails:
  Enabled: true
Rails/ApplicationRecord:
  Exclude:
    - 'lib/**/*'
Metrics/LineLength:
  Max: 120
Metrics/AbcSize:
  Max: 30
Metrics/ClassLength:
  Max: 250
Metrics/ModuleLength:
  Max: 250
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/BlockLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/FormatString:
  Enabled: false
Style/FormatStringToken:
  EnforcedStyle: template
Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Naming/UncommunicativeMethodParamName:
  AllowedNames: [_] # rubocop bug workaround

# 'old' style
Style/EmptyMethod:
  EnforcedStyle: expanded

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/factories/*'

# None-guard clauses are sometimes clearer
Style/GuardClause:
  Enabled: false

# It makes much more sense to group them according to purpose than alphabetically
Bundler/OrderedGems:
  Enabled: false

# This doesn't always make sense
Rails/InverseOf:
  Enabled: false

Rails/HttpPositionalArguments:
  # Broken for
  Exclude:
    - 'spec/requests/api/v1/**/*'

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2

# TODO: Remove once rubocop fixes some bugs
Rails/HasManyOrHasOneDependent:
  Enabled: false
