default: &default
  adapter: postgresql
  encoding: utf-8
  pool: 5

development:
  <<: *default
  database: citadel_dev

test:
  <<: *default
  database: citadel_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *default
  database: citadel_prod
